spring:
 datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/epet?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
     username: root
     password: root
 thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
        content-type: text/html
    cache: false
    suffix: .html
    prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.bdqn.pojo



